<ul class="nav">
	<li<?=$this->layout()->matchedRouteName === 'blog'?' class="active"':''?>>
		<a href="<?=$this->url('blog')?>"><?=$this->translate('home')?></a>
	</li>
	<li class="divider-vertical"></li>
	<li<?=$this->layout()->matchedRouteName === 'blog/post'?' class="active"':''?>>
		<a href="<?=$this->url('blog/post')?>" style="padding-right:5px;"><?=$this->translate('posts')?></a>
	</li>
	<li class="<?=$this->layout()->matchedRouteName === 'blog/post'?'active ':''?>dropdown">
		<a data-toggle="dropdown" class="dropdown-toggle" href="#" style="padding-left:5px;"><b class="caret"></b></a>
		<ul class="dropdown-menu menu-dropdown">
			<li><a href="<?=$this->url('blog/post/create')?>"><?=$this->translate('write_a_new_post')?></a></li>
		</ul>
	</li>
	<li class="divider-vertical"></li>
</ul>