<?php if($this->pageCount > 1){?>
<div class="pagination">
	<ul>
		<?php if(isset($this->previous)){ ?>
		<li><a href="#" onclick="oController.showPosts(<?=$this->escapeJson($this->previous)?>);return false;">«</a></li>
		<?php } ?>
<?php
	//Now put the first page link
	if($this->current > 1 && $this->firstPageInRange > 1){
?>
		<li><a href="#" onclick="oController.showPosts(1);return false;"><?=$this->numberFormat(1)?></a></li>
		<li class="disabled"><a href="#">...</a></li>
<?php
	}
	//Numbered page links
	foreach($this->pagesInRange as $iPage){
?>
		<li<?=($iPage == $this->current)?' class="active"':''?>><a href="#" onclick="oController.showPosts(<?=$this->escapeJson($iPage)?>);return false;"><?=$this->numberFormat($iPage)?></a></li>
<?php
	}
	//Now put the last page link
	if($this->current != $this->last && $this->last > $this->lastPageInRange){
?>
		<li class="disabled"><a href="#">...</a></li>
		<li><a href="#" onclick="oController.showPosts(<?=$this->escapeJson($this->last)?>);return false;"><?=$this->numberFormat($this->last)?></a></li>
<?php
	}
	//Next page link
	if(isset($this->next)){
?>
		<li><a href="#" onclick="oController.showPosts(<?=$this->escapeJson($this->next)?>);return false;">»</a></li>
<?php } ?>
	</ul>
</div>
<?php } ?>