<div class="row-fluid">
	<div class="span12">
		<div class="row-fluid">
			<div class="span12">
				<h4>
					<strong>
						<a href="<?=$this->url('blog/post/read',array(
							'post_id' => $this->post->getPostId(),
							'post_title' =>  $this->post->getPostTitleForUrl(),
						))?>"><?=$this->escapeHtml(ucfirst($this->post->getPostTitle()))?></a>
					</strong>
				</h4>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span2">
				<a class="thumbnail" href="#">
					<img alt="" src="http://placehold.it/260x180">
				</a>
			</div>
			<div class="span10">
				<p><?=$this->escapeHtml(ucfirst($this->post->getPostContentPart()))?></p>
				<hr/>
				<p>
					<a href="<?=$this->url('blog/post/read',array('post_id'=> $this->post->getPostId()))?>" class="btn"><?=$this->escapeHtml($this->translate('read_more'))?></a>
<?php if($this->layout()->loggedUser){ ?>
					<a href="<?=$this->url('blog/post/update',array('post_id' => $this->post->getPostId()))?>" class="btn"><?=$this->escapeHtml($this->translate('update'))?></a>
					<a href="<?=$this->url('blog/post/delete',array('post_id' => $this->post->getPostId()))?>" class="btn btn-danger pull-right" onclick="return confirm(<?=$this->escapeHtmlAttr($this->escapeJson($this->translate('confirm_delete_post')))?>)">
						<i class="icon-warning-sign"></i>
						<?=$this->escapeHtml($this->translate('delete'))?>
					</a>
<?php }?>
				</p>
			</div>
		</div>
		<div class="row-fluid">
			<div class="span12">
				<p></p>
				<p>
					<i class="icon-user"></i> <?=$this->escapeHtml($this->translate('by'))?> <?=$this->userName($this->post->getPostAuthorId())?>
					| <i class="icon-calendar"></i> <?=$this->escapeHtml($this->dateFormat($this->post->getEntityUpdate()?:$this->post->getEntityCreate(),\IntlDateFormatter::MEDIUM))?>
					| <i class="icon-comment"></i> <a href="#">3 Comments</a>
					| <i class="icon-tags"></i> Tags :
					<a href="#"><span class="label label-info">Snipp</span></a>
					<a href="#"><span class="label label-info">Bootstrap</span></a>
					<a href="#"><span class="label label-info">UI</span></a>
					<a href="#"><span class="label label-info">growth</span></a>
				</p>
			</div>
		</div>
	</div>
</div>