<div class="container" data-behavior="BS.Dropdown BS.DismissPopup">
	<header>
		<div class="row">
			<div class="span12">
				<h1><?=$this->translate('application_name')?></h1>
				<div class="row">
					<div class="span6 lead"><?=$this->translate('blog_description')?></div>
					<div class="span6 pull-right"><?=$this->userSection?></div>
				</div>
			</div>
		</div>
		<div class="navbar">
			<div class="navbar-inner">
				<?=$this->navbar?>
			    <form class="navbar-search pull-right">
			    	<input type="text" class="search-query" placeholder="<?=$this->translate('search')?>">
			    </form>
			</div>
		</div>

	</header>
	<!--[if lt IE 7]><p class="chromeframe"><?=$this->translate('outdated_browser')?></p><![endif]-->
	<div class="row-fluid">
		<div class="span12"><?=$this->layout()->content?></div>
	</div>
	<hr>
	<footer><?=$this->footer?></footer>
</div>